config/routes.rb
Rails.application.routes.draw do

  root 'todo_lists#index'

  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout" 

  resources :todo_lists do
    resources :todo_items
  end

  resources :sessions, only: [:new, :create, :destroy]

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
	belongs_to :todo_list
	default_scope -> {order(due_date: :asc)}
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
	before_action :set_todo_list
	before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET /todo_list/:todo_list_id/todo_items
  # GET /todo_list/:todo_list_id/todo_items.json
  #def index
  #  @todo_items = TodoItem.all
  #end

  # GET /todo_list/:todo_list_id/todo_items/:id
  # GET /todo_list/:todo_list_id/todo_items/:id.json
  def show
  end

  # GET /todo_list/:todo_list_id/todo_items/new
  def new
    @todo_item = @todo_list.todo_items.new
  end

  # GET /todo_list/:todo_list_id/todo_items/:id/edit
  def edit
  end

  # POST /todo_list/:todo_list_id/todo_items
  # POST /todo_list/:todo_list_id/todo_items.json
  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to @todo_list, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_list/:todo_list_id/todo_items/:id
  # PATCH/PUT /todo_list/:todo_list_id/todo_items/:id.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_list, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_list/:todo_list_id/todo_items/:id
  # DELETE /todo_list/:todo_list_id/todo_items/:id.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to @todo_list, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
	# Set TodoList
    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:title, :due_date, :description, :completed)
    end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_item]) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
	<% if @todo_item.persisted? %>
  	<div class="field">
    	<%= f.label :completed %><br>
   	 	<%= f.check_box :completed %>
  	</div>
	<% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<h1>Editing Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Show', [@todo_list, @todo_item] %> |
<%= link_to 'Back', @todo_list %>

app/views/todo_items/new.html.erb
<h1>New Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Back', @todo_list %>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo_item.title %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @todo_item.due_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_item.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo_item.completed %>
</p>

<%= link_to 'Edit', edit_todo_list_todo_item_path(@todo_list, @todo_item) %> |
<%= link_to 'Back', @todo_list %>